export {default as Home} from './home/Home'
export {default as Contact} from './contact/Contact'
// export {default as Cart} from './cart/Cart'
// export {default as Admin} from './myprofile/MyProfile'
// export {default as orderHistory} from './orderHistory/OrderHistory'
export {default as Login} from './auth/Login'
export {default as Logout} from './auth/Logout'
export {default as Register} from './auth/Register'
export {default as Reset} from './auth/Reset'
export {default as MyProfile} from './myprofile/MyProfile'
export {default as Ad} from './ad/Ad'
export {default as Ads} from './ads/Ads'
export {default as Products} from "./product/product"
// export {default as OrderHistory} from './orderHistory/OrderHistory'